export const surpriseMePrompts = [
  'A painting of LeBron James as a Renaissance king',
  'A painting of a tennis match under starry skies, inspired by Van Gogh',
  'A painting of a soccer ball mid-kick, done in an abstract style',
  'A painting of Tiger Woods playing golf in a surrealist dreamscape',
  'A painting of Michelangelo’s David as a basketball player',
  'A painting of a graffiti-style tennis court featuring Roger Federer',
  'A painting of a cubist soccer game in an urban park',
  'A painting of an impressionist rugby scrum in a field',
  'A painting of Rafael Nadal as an ancient Greek warrior',
  'A painting of a modernist figure skater',
  'A painting of Cristiano Ronaldo in a futuristic cyber arena',
  'A painting of a surrealist swimming race in the clouds',
  'A painting of a marathon runner on fire, done in abstract art style',
  'A painting of an impressionist basketball game in the rain',
  'A painting of Serena Williams as a Greek goddess in tennis',
  'A watercolor painting of a soccer goal celebration',
  'A painting of Tiger Woods on an abstract golf course',
  'A painting of a cyclist racing through an alien landscape',
  'A painting of a futuristic tennis match with glowing rackets',
  'A painting of a surrealist soccer match in a desert',
  'A volleyball spike inspired by Frida Kahlo',
  'A modern art boxing ring with Muhammad Ali',
  'A painting of Cristiano Ronaldo kicking a glowing orb',
  'A painting of Lionel Messi dribbling through a kaleidoscope',
  'A graffiti street soccer match featuring Neymar Jr.',
  'A painting of Vincent van Gogh painting a basketball court',
  'A surrealist soccer game painted by Salvador Dalí',
  'An impressionist painting of a hockey fight',
  'A futuristic race with abstract motion',
  'A painting of Kobe Bryant dunking over an abstract skyline',
  'A painting of Pele as a mythical soccer hero',
  'A pop art tennis match with Venus Williams',
  'A dreamscape painting of Michael Jordan dunking',
  'A surreal figure skating event on a melting rink',
  'A painting of Rafael Nadal on a glowing clay court',
  'A watercolor painting of a baseball game in a storm',
  'A futuristic Olympic track race',
  'A painting of Messi kicking a glowing soccer ball',
  'A painting of a cyclist speeding through the city in an abstract style',
  'A surrealist tennis serve with melting rackets',
  'A painting of Serena Williams in a pop art tennis arena',
  'A painting of Cristiano Ronaldo scoring on a neon field',
  'A painting of Lionel Messi in an alien soccer match',
  'A painting of Tiger Woods teeing off on Mars',
  'A painting of a Vincent van Gogh-inspired basketball slam dunk',
  'A painting of surrealist marathon runners on a floating track',
  'A painting of an abstract MMA fight in a futuristic cage',
  'A painting of David Beckham kicking a glowing soccer ball',
  'An impressionist volleyball game on the beach',
  'A painting of Michael Phelps swimming through clouds',
  'A pop art boxer in a boxing ring',
  'A Renaissance-style painting of a soccer goalie',
  'A painting of a cyclist racing through a surrealist city',
  'A painting of Cristiano Ronaldo as a superhero on the field',
  'A painting of Messi dribbling through an abstract maze',
  'A surrealist tennis match with melting rackets',
  'An impressionist football game under a sunset',
  'A painting of Serena Williams in a futuristic tennis stadium',
  'A painting of LeBron James dunking in a cubist painting',
  'A painting of Lionel Messi scoring in a Renaissance stadium',
  'A soccer celebration inspired by Frida Kahlo',
  'A pop art swimming race in neon water',
  'A painting of Kobe Bryant in an abstract basketball court',
  'A modernist hockey game in a storm',
  'A painting of Cristiano Ronaldo in a sci-fi soccer game',
  'A painting of Michael Jordan as a Greek god in basketball',
  'A surrealist marathon on a rainbow road',
  'A cubist painting of rugby players tackling each other',
  'A painting of Rafael Nadal in a dreamlike tennis court',
  'A watercolor painting of a soccer match in a thunderstorm',
  'A painting of Tiger Woods in a futuristic golf tournament',
  'An impressionist tennis match on the moon',
  'A painting of abstract soccer players in motion',
  'A painting of David Beckham scoring in a surreal stadium',
  'A painting of Kobe Bryant in a cosmic basketball game',
  'A painting of Lionel Messi playing soccer in a neon city',
  'A graffiti soccer mural featuring Cristiano Ronaldo',
  'A figure skating performance inspired by Frida Kahlo',
  'A pop art volleyball match on the beach',
  'A painting of Rafael Nadal serving in a futuristic arena',
  'A painting of Tiger Woods in a surrealist golf landscape',
  'A dreamlike soccer game with Cristiano Ronaldo',
  'A cubist painting of a cyclist racing through a city',
  'A painting of LeBron James dunking in a sci-fi world',
  'A surrealist swimming competition in the sky',
  'A figure skating performance inspired by Frida Kahlo',
  'A pop art MMA fight in a neon arena',
  'A painting of Serena Williams serving in a dreamlike court',
  'An abstract urban basketball court featuring Michael Jordan',
  'A painting of Cristiano Ronaldo kicking a glowing football in space',
  'A painting of LeBron James as an ancient Roman warrior in basketball',
  'A futuristic soccer game with Messi on Mars',
  'An impressionist tennis match featuring Roger Federer',
  'A pop art race on a glowing track',
  'A painting of Kobe Bryant as a superhero in basketball',
  'A painting of David Beckham playing soccer in a melting stadium',
  'A surrealist marathon with glowing paths',
  'A cubist hockey match in an icy arena',
  'A cosmic game with Cristiano Ronaldo',
  'A tennis match inspired by Frida Kahlo featuring Venus Williams',
];
